### ISSUE TITLE
Orientation?

### ISSUE THREAD

**Issue by lamlengend98** [AndreYonadam/react-native-scrolling-images#1]
Does it work with Orientation, i set landscape but image is portrait

`<ScrollingBackground
        style={{
          backgroundColor: '#0B7483',
        }}
        resizeMode="contain"
        speed={2}
        direction={'left'}
        images={[BG1, BG2, BG3, BG4]}
      />`

**Comment by AndreYonadam** [comment]
There is no property to set the orientation of your image. You will have to do that manually. `direction` only specifies the direction that the image is scrolling.
